Resources:
  udacityEKS:
    Type: AWS::EKS::Cluster
    Properties: 
      Name: myEKSCluster
      ResourcesVpcConfig: 
        EndpointPrivateAccess: False
        EndpointPublicAccess: True
        PublicAccessCidrs: 
          - 0.0.0.0/0
        SecurityGroupIds: 
          - sg-0f0b4901febdb5243
        SubnetIds: 
          - subnet-023696bf7d53b2979
          - subnet-03fde165199a5159c
          - subnet-01de1932b4eeb0378
      RoleArn: arn:aws:iam::910475624256:role/myEKSClusterRole
